# Generated by Django 5.0.4 on 2024-05-27 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=100)),
                ('source_subtype', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('destination_type', models.CharField(max_length=100)),
                ('destination_subtype', models.CharField(max_length=100)),
                ('project_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project_team')),
            ],
        ),
    ]
