# Generated by Django 5.0.4 on 2024-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='flow_num',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
