# Generated by Django 5.0.4 on 2024-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_master_flow_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='two_way',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
