# Generated by Django 5.0.4 on 2024-06-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_master_two_way'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100)),
                ('version_timestamp', models.CharField(max_length=100)),
                ('mapping', models.CharField(max_length=100)),
                ('project_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project_team')),
            ],
        ),
    ]
